# Generated by Django 5.0.7 on 2024-07-20 00:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('servey_bl', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['createdAt'], 'verbose_name_plural': 'categories'},
        ),
        migrations.RenameField(
            model_name='category',
            old_name='created',
            new_name='createdAt',
        ),
        migrations.RenameField(
            model_name='category',
            old_name='updated',
            new_name='updatedAt',
        ),
    ]
